import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Keyboard Diagnostics Tool</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className='text-3xl text-gray-600'>  Keyboard Diagnostic (0hr & -50min due) </h1>
        <div className='text-gray-600'> 
          <Link href='mac'> Mac </Link> <br/>
          <Link href='win'> Windows </Link>
        </div>
      </main>
    </>
  )
}
``